#!/bin/bash

# Function to display information about a subdomain
display_info() {
    local subdomain=$1
    local domain=$2
    local result=$(dig $subdomain.$domain | awk '/ANSWER SECTION/{getline; print}')
    local record_type=$(echo $result | awk '{print $3}')
    local destination=$(echo $result | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main function to handle input arguments and display information accordingly
main() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            display_info $sub $domain
        done
    else
        display_info $subdomain $domain
    fi
}

# Check if arguments are provided
if [ "$#" -eq 0 ]; then
    echo "Error: Domain name is mandatory"
    exit 1
fi

main "$@"

