#!/bin/bash

# Define the filename for the private key
private_key="school"

# Number of bits for the key
bits="4096"

# Passphrase to protect the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b "$bits" -N "$passphrase" -f "$private_key"

# Check if the key generation was successful
if [ $? -eq 0 ]; then
    echo "RSA key pair successfully created."
    ls -l "$private_key" "$private_key.pub"
else
    echo "Error: Failed to create RSA key pair."
fi

